AOSP_TOP_ABS := $(realpath .)

KERNEL_DTB_FILE_PP11 := allwinner/sun50i-a64-pinephone-1.1.dtb
KERNEL_DTB_FILE_PP12 := allwinner/sun50i-a64-pinephone-1.2.dtb

KERNEL_OUT		:= $(PRODUCT_OUT)/obj/GLODROID/KERNEL
KERNEL_DTB_OUT		:= $(KERNEL_OUT)/install/dtbs
GEN_DTBCFG		:= $(PRODUCT_OUT)/gen/DTBO/dtbo.cfg

ifneq ($(GD_NO_DEFAULT_GEN_DTBCFG),)
$(GEN_DTBCFG):
	mkdir -p $(dir $@)
	echo "# DTBO image configuration file for GloDroid project. Autogenerated, do not change!" > $@
	echo "  page_size=4096" >> $@
	echo "$(AOSP_TOP_ABS)/$(KERNEL_DTB_OUT)/$(KERNEL_DTB_FILE_PP11)" >> $@
	echo "  id=0x00000011" >> $@
	echo "$(AOSP_TOP_ABS)/$(KERNEL_DTB_OUT)/$(KERNEL_DTB_FILE_PP12)" >> $@
	echo "  id=0x00000012" >> $@
	echo "$(AOSP_TOP_ABS)/$(ANDROID_DTBO)" >> $@
	echo "  id=0x00000FFF" >> $@
endif
